# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Thomas Byttebier
description: Personal website of Thomas Byttebier, freelance digital designer. Based in Ghent, Belgium.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://thomasbyttebier.be" # the base hostname & protocol for your site
timezone: Europe/Brussels

# Build settings
markdown: kramdown
